baseURL = 'https://blog.vertsineu.top/'
locale = 'en-us'
title = "Vertsineu's Blog"
theme = 'PaperMod'

[params]
    env = 'production'
    defaultTheme = 'auto'
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    math = true

[params.homeInfoParams]
  Title = "Hi there \U0001F44B"
  Content = "Welcome to my blog! I'm Vertsineu, an undergraduate student majoring in Computer Science at the University of Science and Technology of China (USTC). Here is where I share my thoughts on tech, life, and everything in between. Feel free to explore and connect with me through the links below!"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/Vertsineu"

[[params.socialIcons]]
    name = "forgejo"
    url = "https://git.vertsineu.top/Vertsineu"

[[params.socialIcons]]
    name = "email"
    url = "mailto:vertsineu@gmail.com"

[markup.typst]
    root = "./content"
    packagePath = "./packages"
    jobs = 4

[markup.typst.watch]
    enabled = true
    timeout = "3s"

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 20

[[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30
